# Generated by Django 5.1.6 on 2025-04-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_recipeimage_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='recipe_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
